### ISSUE TITLE
Implement shiny instruction (Random)

### ISSUE THREAD

**Issue by cbebe** [Fysh-Fyve/riscv#4]
We are creating a 32-bit random number instruction!

We just have a hardware component that reads from the 12-bit ADC every clock cycle and shifting the previously-read bits at the same time. The instruction just then moves it to `rd`. 

### Tasks
- [x] Create hardware component
- [x] Create instruction encoding
- [x] Implement the operation in the Control FSM
